// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client_queries.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createNewClient = `-- name: CreateNewClient :one
INSERT INTO clients (user_id, name, email, invoice_link)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateNewClientParams struct {
	UserID      uuid.UUID
	Name        string
	Email       string
	InvoiceLink string
}

func (q *Queries) CreateNewClient(ctx context.Context, arg CreateNewClientParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createNewClient,
		arg.UserID,
		arg.Name,
		arg.Email,
		arg.InvoiceLink,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getAllClients = `-- name: GetAllClients :many
SELECT id, user_id, name, email, invoice_link, created_at FROM clients
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetAllClients(ctx context.Context, userID uuid.UUID) ([]Client, error) {
	rows, err := q.db.Query(ctx, getAllClients, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Email,
			&i.InvoiceLink,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClientByUUID = `-- name: GetClientByUUID :one
SELECT id, user_id, name, email, invoice_link, created_at FROM clients 
WHERE id = $1
`

func (q *Queries) GetClientByUUID(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByUUID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.InvoiceLink,
		&i.CreatedAt,
	)
	return i, err
}
