// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client_queries.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createNewClient = `-- name: CreateNewClient :one
INSERT INTO clients (user_id, name, email, invoice_link)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateNewClientParams struct {
	UserID      uuid.UUID
	Name        string
	Email       string
	InvoiceLink string
}

func (q *Queries) CreateNewClient(ctx context.Context, arg CreateNewClientParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createNewClient,
		arg.UserID,
		arg.Name,
		arg.Email,
		arg.InvoiceLink,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getClientByUUID = `-- name: GetClientByUUID :one
SELECT id, user_id, name, email, invoice_link, created_at FROM clients 
WHERE id = $1 AND user_id = $1
`

func (q *Queries) GetClientByUUID(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByUUID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.InvoiceLink,
		&i.CreatedAt,
	)
	return i, err
}
