// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client_queries.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createNewClient = `-- name: CreateNewClient :exec
INSERT INTO clients (user_id, name, email, invoice_link)
VALUES ($1, $2, $3, $4)
`

type CreateNewClientParams struct {
	UserID      uuid.UUID
	Name        string
	Email       string
	InvoiceLink string
}

func (q *Queries) CreateNewClient(ctx context.Context, arg CreateNewClientParams) error {
	_, err := q.db.Exec(ctx, createNewClient,
		arg.UserID,
		arg.Name,
		arg.Email,
		arg.InvoiceLink,
	)
	return err
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, user_id, name, email, invoice_link, created_at FROM clients 
WHERE id = $1
`

func (q *Queries) GetClientByID(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.InvoiceLink,
		&i.CreatedAt,
	)
	return i, err
}
