// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_jobs_queries.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailJob = `-- name: CreateEmailJob :exec
INSERT INTO email_jobs (client_id, send_at)
VALUES ($1, $2)
`

type CreateEmailJobParams struct {
	ClientID uuid.UUID
	SendAt   pgtype.Timestamptz
}

func (q *Queries) CreateEmailJob(ctx context.Context, arg CreateEmailJobParams) error {
	_, err := q.db.Exec(ctx, createEmailJob, arg.ClientID, arg.SendAt)
	return err
}

const getEmailJobByID = `-- name: GetEmailJobByID :one
SELECT id, client_id, status, send_at, sent_at, created_at
FROM email_jobs
WHERE id = $1
`

func (q *Queries) GetEmailJobByID(ctx context.Context, id uuid.UUID) (EmailJob, error) {
	row := q.db.QueryRow(ctx, getEmailJobByID, id)
	var i EmailJob
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Status,
		&i.SendAt,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingEmailJobs = `-- name: GetPendingEmailJobs :many
SELECT id, client_id, status, send_at, sent_at, created_at
FROM email_jobs
WHERE status = 'pending'
AND send_at <= NOW()
`

func (q *Queries) GetPendingEmailJobs(ctx context.Context) ([]EmailJob, error) {
	rows, err := q.db.Query(ctx, getPendingEmailJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailJob
	for rows.Next() {
		var i EmailJob
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Status,
			&i.SendAt,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobAsCompleted = `-- name: MarkJobAsCompleted :exec
UPDATE email_jobs
SET status = 'completed', sent_at = NOW()
WHERE id = $1 
AND status = 'processing'
`

func (q *Queries) MarkJobAsCompleted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markJobAsCompleted, id)
	return err
}

const markJobAsFailed = `-- name: MarkJobAsFailed :exec
UPDATE email_jobs
SET status = 'failed'
WHERE id = $1
AND (status = 'pending' OR status = 'processing')
`

func (q *Queries) MarkJobAsFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markJobAsFailed, id)
	return err
}

const tryMarkJobAsProcessing = `-- name: TryMarkJobAsProcessing :execrows
UPDATE email_jobs
SET status = 'processing'
WHERE id = $1
AND status = 'pending'
`

func (q *Queries) TryMarkJobAsProcessing(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, tryMarkJobAsProcessing, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
