// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Client struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Email       string
	InvoiceLink string
	CreatedAt   pgtype.Timestamp
}

type EmailJob struct {
	ID        uuid.UUID
	ClientID  uuid.UUID
	Status    string
	SendAt    pgtype.Timestamptz
	SentAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID        uuid.UUID
	Email     string
	Password  string
	CreatedAt pgtype.Timestamptz
}
