// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateEmailJob(ctx context.Context, arg CreateEmailJobParams) error
	CreateNewClient(ctx context.Context, arg CreateNewClientParams) (uuid.UUID, error)
	CreateNewUser(ctx context.Context, arg CreateNewUserParams) error
	GetAllClients(ctx context.Context, userID uuid.UUID) ([]Client, error)
	GetAllEmailJobs(ctx context.Context) ([]EmailJob, error)
	GetClientByUUID(ctx context.Context, id uuid.UUID) (Client, error)
	GetEmailJobByID(ctx context.Context, id uuid.UUID) (EmailJob, error)
	GetPendingEmailJobs(ctx context.Context) ([]EmailJob, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	MarkJobAsCompleted(ctx context.Context, id uuid.UUID) error
	MarkJobAsFailed(ctx context.Context, id uuid.UUID) error
	TryMarkJobAsProcessing(ctx context.Context, id uuid.UUID) (int64, error)
}

var _ Querier = (*Queries)(nil)
