// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateNewClient(ctx context.Context, arg CreateNewClientParams) error
	CreateNewUser(ctx context.Context, arg CreateNewUserParams) error
	GetClientByID(ctx context.Context, id uuid.UUID) (Client, error)
	GetEmailJobByID(ctx context.Context, id uuid.UUID) (EmailJob, error)
	GetPendingEmailJobs(ctx context.Context) ([]EmailJob, error)
	GetUserByName(ctx context.Context, email string) (GetUserByNameRow, error)
	MarkJobAsCompleted(ctx context.Context, id uuid.UUID) error
	MarkJobAsFailed(ctx context.Context, id uuid.UUID) error
	TryMarkJobAsProcessing(ctx context.Context, id uuid.UUID) (int64, error)
}

var _ Querier = (*Queries)(nil)
