// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_queries.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createNewUser = `-- name: CreateNewUser :exec
INSERT INTO users (email, password)
VALUES ($1, $2)
`

type CreateNewUserParams struct {
	Email    string
	Password string
}

func (q *Queries) CreateNewUser(ctx context.Context, arg CreateNewUserParams) error {
	_, err := q.db.Exec(ctx, createNewUser, arg.Email, arg.Password)
	return err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, email, password FROM users
WHERE email = $1
`

type GetUserByNameRow struct {
	ID       uuid.UUID
	Email    string
	Password string
}

func (q *Queries) GetUserByName(ctx context.Context, email string) (GetUserByNameRow, error) {
	row := q.db.QueryRow(ctx, getUserByName, email)
	var i GetUserByNameRow
	err := row.Scan(&i.ID, &i.Email, &i.Password)
	return i, err
}
