// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_queries.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createNewUser = `-- name: CreateNewUser :exec
INSERT INTO users (email, password)
VALUES ($1, $2)
`

type CreateNewUserParams struct {
	Email    string
	Password string
}

func (q *Queries) CreateNewUser(ctx context.Context, arg CreateNewUserParams) error {
	_, err := q.db.Exec(ctx, createNewUser, arg.Email, arg.Password)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID       uuid.UUID
	Email    string
	Password string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(&i.ID, &i.Email, &i.Password)
	return i, err
}
